// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gloyr5gen.Repository.Concrete.EntityFramework;

namespace gloyr5gen.Migrations
{
    [DbContext(typeof(GloyrContext))]
    [Migration("20190926193914_UpdateAdvertisement")]
    partial class UpdateAdvertisement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("gloyr5gen.Entity.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HtmlContent");

                    b.Property<string>("Image");

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsFeatured");

                    b.Property<bool>("IsHome");

                    b.Property<string>("acikadres");

                    b.Property<string>("aciklama");

                    b.Property<double>("baslangicmaas");

                    b.Property<double>("bitismaas");

                    b.Property<string>("calismasekli");

                    b.Property<string>("egitimdurumu");

                    b.Property<string>("firmasektoru");

                    b.Property<string>("ilanName");

                    b.Property<DateTime>("paylasimtarihi");

                    b.Property<string>("pozisyonseviyesi");

                    b.Property<string>("sehir");

                    b.Property<string>("tecrube");

                    b.Property<string>("ulke");

                    b.HasKey("AdvertisementId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("gloyr5gen.Entity.AdvertisementCategory", b =>
                {
                    b.Property<int>("AdvertisementId");

                    b.Property<int>("CategoryId");

                    b.HasKey("AdvertisementId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AdvertisementCategory");
                });

            modelBuilder.Entity("gloyr5gen.Entity.CalismaSekli", b =>
                {
                    b.Property<int>("CalismaSekliId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvertisementId");

                    b.Property<string>("calismaseklibilgi");

                    b.HasKey("CalismaSekliId");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("CalismaSeklis");
                });

            modelBuilder.Entity("gloyr5gen.Entity.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.Property<string>("Categoryaciklama");

                    b.Property<string>("Image");

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsFeatured");

                    b.Property<bool>("IsHome");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("gloyr5gen.Entity.Sehir", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvertisementId");

                    b.Property<string>("SehirName");

                    b.HasKey("SehirId");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("Sehirs");
                });

            modelBuilder.Entity("gloyr5gen.Entity.ulke", b =>
                {
                    b.Property<int>("ulkeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ulkename");

                    b.HasKey("ulkeId");

                    b.ToTable("ulkes");
                });

            modelBuilder.Entity("gloyr5gen.Entity.ulkecategory", b =>
                {
                    b.Property<int>("ulkecategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SehirId");

                    b.Property<int>("ulkeId");

                    b.HasKey("ulkecategoryId");

                    b.HasIndex("SehirId");

                    b.HasIndex("ulkeId");

                    b.ToTable("ulkecategory");
                });

            modelBuilder.Entity("gloyr5gen.Entity.AdvertisementCategory", b =>
                {
                    b.HasOne("gloyr5gen.Entity.Advertisement", "Advertisement")
                        .WithMany("AdvertisementCategories")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("gloyr5gen.Entity.Category", "Category")
                        .WithMany("AdvertisementCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gloyr5gen.Entity.CalismaSekli", b =>
                {
                    b.HasOne("gloyr5gen.Entity.Advertisement", "Advertisement")
                        .WithMany("CalismaSeklis")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gloyr5gen.Entity.Sehir", b =>
                {
                    b.HasOne("gloyr5gen.Entity.Advertisement", "Advertisement")
                        .WithMany("Sehirs")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("gloyr5gen.Entity.ulkecategory", b =>
                {
                    b.HasOne("gloyr5gen.Entity.Sehir", "Sehir")
                        .WithMany("Ulkecategories")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("gloyr5gen.Entity.ulke", "ulke")
                        .WithMany("Ulkecategories")
                        .HasForeignKey("ulkeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
